language: python
sudo: false

python:
    - "3.5"
    - "3.6"

install:
    - pip install tox
    - pip install codecov

script:
    - coverage run tests/test_frbz.py
    - tox -v -e py

after_success:
    - codecov
