language: python
os: linux
dist: xenial
sudo: false

python:
    - "3.5"
    - "3.6"
    - "3.7"

install:
    - pip install pytest-cov
    - pip install codecov
    - pip install -r requirements.txt

script:
    - pytest --cov=fruitbat/.

after_success:
    - codecov
